### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by drawingfrommemory** [raafirivero/dunk-child#1]
Just wanted to say thanks for this, I wanted to override the flatsome_add_to_cart_dropdown as well without touching the parent theme, and I had to call it in the 'after_setup_theme' hook, but it wasn't working. Adding the '15' from your code fixed it. How did you know to add that priority?

```
add_action( 'after_setup_theme', 'remove_parent_theme_features', 15 );
```

For anyone else struggling with this, I also have to call sessionStorage.clear(); in the javascript console as well when testing because woocommerce essentially caches the request  (in cart-fragments.min.js).

**Comment by raafirivero** [comment]
Can't remember where I learned to set that priority, but once it worked it was a big relief. :) Cheers.
